name: Automatic

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review] # Added "ready_for_review" to automatically trigger run when going outside of draft

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  reusable:
    name: Reusable launch
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
