name: Automatic

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review] # Added "ready_for_review" to automatically trigger run when going outside of draft

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  ref:
    name: print ref
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.merge_commit_sha }}
      - name: Read informations
        id: information_reading
        uses: actions/github-script@v6
        env:
          PULL_REQUEST_ID: ${{ github.event.pull_request }}
        with:
          script: |
            const { PULL_REQUEST_ID } = process.env
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: PULL_REQUEST_ID
            }
            console.log(JSON.stringify(request, null, 4));
          result-encoding: string

  reusable:
    name: Reusable launch
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
