name: Automatic

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review] # Added "ready_for_review" to automatically trigger run when going outside of draft

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  print:
    name: print ref
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.issue-number }}

  ref:
    name: Get Pull Request info
    uses: ./.github/workflows/pull_request_information_reading.yaml
    with:
      pull_request_id: ${{ github.event.inputs.pull_request_id }}

  reusable:
    name: Reusable launch
    needs: ref
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ needs.ref.outputs.merge_commit_sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
