name: Comment

on:
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  pull_request:
    name: Get Pull Request info
    if: ${{ github.event.issue.pull_request }}
    uses: ./.github/workflows/pull_request_information_reading.yaml
    with:
      pull_request_id: ${{ github.event.issue.number }}

  reusable:
    name: Reusable launch
    if: ${{ github.event.issue.pull_request }}
    needs: pull_request
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ needs.pull_request.outputs.merge_commit_sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
