name: Comment

on:
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true


jobs:
  reusable:
    name: Reusable launch
    uses: ./.github/scripts/reusable.yaml
