name: Comment

on:
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  display_ref:
    name: display-ref-event
    runs-on: ubuntu-latest
    steps:
      - name: Ref definition
        id: ref_definition
        uses: actions/github-script@v6
        env:
          EVENT: ${{ github.event }}
        with:
          script: |
            const { EVENT } = process.env;
            console.log(JSON.stirngify(EVENT, null, 4);

  reusable:
    name: Reusable launch
    if: contains(github.event.comment.html_url, '/pull/')
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
