name: Manual

on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: Pull request id
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  manual_tests:
    name: Manual tests
    runs-on: ubuntu-latest
    steps:
      - name: Ref definition
        id: ref_definition
        uses: actions/github-script@v3
        with:
          script: |
            const request = {
              owner: context.repor.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_id }}
            }
            try {
              const result = await github.pulls.get(request);
              return result.data;
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - run: echo "${{ steps.ref_definition.outputs.result }}"
      - name: Reusable launch
        uses: ./.github/workflows/reusable.yaml
        with:
          ref: ${{ github.event.inputs.pr_id }}
