name: Manual

on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: Pull request id
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  ref:
    name: Get Pull Request info
    uses: ./.github/workflows/pull_request_information_reading.yaml
    with:
      pull_request_id: ${{ github.event.inputs.pull_request_id }}

  reusable:
    name: Reusable launch
    needs: ref
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: ${{ needs.ref.outputs.merge_commit_sha }}
