name: Manual

on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: Pull request id
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Cancel running actions if branch get pushed
  cancel-in-progress: true

jobs:
  reusable:
    name: Reusable launch
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/reusable.yaml
    with:
      ref: pull/${{ github.event.inputs.pr_id }}/head
