name: Pull request information reading
on:
  workflow_call:
    inputs:
      pull_request_id:
        type: string
        required: true
    outputs:
      merge_commit_sha:
        description: "Pull request merge commit sha"
        value: ${{ jobs.pull_request_read.outputs.merge_commit_sha }}

jobs:
  pull_request_read:
    name: Read Pull Request SHA
    runs-on: ubuntu-latest
    outputs:
      merge_commit_sha: ${{ steps.information_reading.outputs.result }}
    steps:
      - run:
          echo ${{ inputs.pull_request_id }}
      - name: Read informations
        id: information_reading
        uses: actions/github-script@v6
        env:
          PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        with:
          script: |
            const { PULL_REQUEST_ID } = process.env
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: PULL_REQUEST_ID
            }
            console.log(JSON.stringify(request, null, 4));
            try {
              const result = await github.rest.pulls.get(request);
              return merge_commit_sha: result.data.merge_commit_sha;
            } catch (err) {
              core.setFailed(`Pull request retireval failed with error ${err}`)
            }
