name: Reusable
on:
  workflow_call:

jobs:
  witness:
    name: Test Output
    runs-on: ubuntu-latest
    steps:
      - name: Read text file
        id: test
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test.txt
      - name: Echo
        run: echo "${{ steps.test.outputs.content }}"
