name: Reusable
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      required_check:
        type: boolean
        required: false
        default: false
    secrets:
      token:
        required: true

jobs:
  witness:
    name: Test Output
    runs-on: ubuntu-latest
    steps:
      - name: Ref
        run: echo "current ref is ${{ inputs.ref }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Read text file
        id: file-dev
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test.txt
      - name: Echo
        run: echo "${{ steps.file-dev.outputs.content }}"
      - name: Read text file
        id: file-branch
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test-branch.txt
      - name: Echo
        run: echo "${{ steps.file-branch.outputs.content }}"
      - uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ inputs.required_check }}
        with:
          token: ${{ secrets.token }}
          name: Check 1
          conclusion: success
      - uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ !inputs.required_check }}
        with:
          token: ${{ secrets.token }}
          name: Check 2
          conclusion: success
