name: Run-unit-test

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./iluvcoffee

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/Checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test